source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gem 'puma'
gem 'rails'

gem 'kit-app_container', path: '../../libraries/kit-app_container' # DEV MODE
gem 'kit-auth',          path: '../../domains/kit-auth' # DEV MODE
#gem 'kit-geolocation',   path: '../../domains/kit-geolocation' # DEV MODE
#gem 'kit-payment',       path: '../../domains/kit-payment' # DEV MODE

group :development do
  gem 'listen'

  gem 'better_errors'

  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'

  gem 'awesome_print'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  #gem 'capybara', '>= 2.15'
  #gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  #gem 'chromedriver-helper'

  gem 'database_cleaner'
  gem 'factory_bot_rails', require: false
  gem 'faker'
  gem 'fuubar'
  gem 'rspec-rails'
  gem 'timecop'
  gem 'vcr', '~> 4.0'
  gem 'webmock', '~> 2.1'
end

# DEV MODE ---------------------------------------------------------------------

gem 'kit-active_admin', path: '../../libraries/kit-active_admin', require: 'kit/active_admin' # DEV MODE
gem 'kit-contract',     path: '../../libraries/kit-contract' # DEV MODE
gem 'kit-doc',          path: '../../libraries/kit-doc' # DEV MODE
gem 'kit-domain',       path: '../../libraries/kit-domain' # DEV MODE
gem 'kit-engine',       path: '../../libraries/kit-engine' # DEV MODE
gem 'kit-error',        path: '../../libraries/kit-error' # DEV MODE
gem 'kit-log',          path: '../../libraries/kit-log' # DEV MODE
gem 'kit-organizer',    path: '../../libraries/kit-organizer' # DEV MODE
gem 'kit-pagination',   path: '../../libraries/kit-pagination' # DEV MODE
gem 'kit-router',       path: '../../libraries/kit-router' # DEV MODE
