source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gem 'puma'
gem 'rails'

gem 'kit-app-container', path: '../../libraries/kit-app-container' # DEV MODE
gem 'kit-auth',          path: '../../domains/kit-auth' # DEV MODE
gem 'kit-geolocation',   path: '../../domains/kit-geolocation' # DEV MODE
gem 'kit-payment',       path: '../../domains/kit-payment' # DEV MODE

group :development do
  gem 'listen'

  gem 'better_errors'

  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'

  gem 'awesome_print'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  #gem 'capybara', '>= 2.15'
  #gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  #gem 'chromedriver-helper'

  gem 'database_cleaner'
  gem 'factory_bot_rails', require: false
  gem 'faker'
  gem 'fuubar'
  gem 'rspec-rails'
  gem 'timecop'
  gem 'vcr', '~> 4.0'
  gem 'webmock', '~> 2.1'
end
