inherit_from:
  - .rubocop_shared.yml

AllCops:

  Exclude:
    - '**/Gemfile.lock'
    - 'apps/**/*'
    - 'domains/**/*'
    - 'libraries/kit-api/spec/dummy/db/schema.rb'
    - 'libraries/kit-doc-yard/specs/dummy/**/*.rb'
    - 'libraries/kit-doc-yard/node_modules/**/*'
    - 'libraries/kit-active-admin/**/*'
    - 'libraries/kit-dotenv/**/*'

# ------------------------------------------------------------------------------

# Re-add config/default.yml parameters for nested spec directories.
# Reference: https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
#
# Weirdly enough this is only applied when specifying the config file with `rubocop --config .rubocop.yml`

Naming/PredicateName:
  Exclude:
    - 'libraries/*/spec/**/*'

Style/Documentation:
  Exclude:
    - 'libraries/*/spec/**/*'

Style/DocumentationMethod:
  Exclude:
    - 'libraries/*/spec/**/*'

Style/NumericPredicate:
  Exclude:
    - 'libraries/*/spec/**/*'

# ------------------------------------------------------------------------------
