# Reference: https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

AllCops:

  TargetRubyVersion: 2.7
  NewCops: enable


# Layouts ----------------------------------------------------------------------

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  #EnforcedStyle: empty_lines
  Enabled: false

# NOTE: Prevents some block alignment.
Layout/ExtraSpacing:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/RedundantCopDisableDirective:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space


# Lint -------------------------------------------------------------------------

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

# NOTE: gets it wrong when you want to avoid usage of **
Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

Lint/UnusedMethodArgument:
  Enabled: false


# Metrics ----------------------------------------------------------------------

Metrics:
  Enabled: false


# Naming -----------------------------------------------------------------------

Naming/ConstantName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false


# Style ------------------------------------------------------------------------

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# REF: https://docs.rubocop.org/rubocop/cops_style.html#stylecombinableloops
Style/CombinableLoops:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/ConditionalAssignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

# REF: https://docs.rubocop.org/rubocop/cops_style.html#stylehashaslastarrayitem
Style/HashAsLastArrayItem:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/NegatedIf:
  Enabled: false

# NOTE: Gets it wrong when it's a no op
Style/Next:
  Enabled: false

Style/NilComparison:
  EnforcedStyle: comparison

Style/NonNilCheck:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantInterpolation:
  Enabled: false

# NOTE: Gets it wrong on empty return.
Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/SingleLineMethods:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  #Enabled: false
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses

Style/WhileUntilDo:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
