AllCops:

  TargetRubyVersion: 2.7

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/DoubleNegation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Style/NegatedIf:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses

Style/ConditionalAssignment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/MultilineBlockChain:
  Enabled: false

# Gets it wrong when it's a no op
Style/Next:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

# Gets it wrong when you want to avoid usage of **
Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

# Gets it wrong on empty return.
Style/RedundantReturn:
  Enabled: false

# Prevents some block alignment.
Layout/ExtraSpacing:
  Enabled: false

# Indentation related

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented


# Empty lines / spaces

Layout/EmptyLinesAroundModuleBody:
  #EnforcedStyle: empty_lines
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/LeadingCommentSpace:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty


# Lambda
Style/Lambda:
  EnforcedStyle: literal


# Hash / Array

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line


# Visual blocks

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent


# Methods

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/MethodCallWithoutArgsParentheses:
  Enabled: false


# Commas

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  #Enabled: false
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma


# Predicates

Style/NumericPredicate:
  Enabled: false

Style/NilComparison:
  EnforcedStyle: comparison

Style/ZeroLengthPredicate:
  Enabled: false


# Required by Rubocop

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Style/ExponentialNotation:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true
