source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gemspec

gem 'kit-app_container',       path: '../../libraries/kit-app_container' # DEV MODE
gem 'kit-contract',            path: '../../libraries/kit-contract'
gem 'kit-dummy_app_container', path: '../../libraries/kit-dummy_app_container' # DEV MODE
gem 'kit-organizer',           path: '../../libraries/kit-organizer' # DEV MODE

group :test, :development do
  gem 'pry'
end
