source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gemspec name: 'kit-dotenv'
gemspec name: 'kit-dotenv-rails'

gem 'kit-doc-yard', path: '../../libraries/kit-doc-yard'

group :test, :development do
  gem 'pry'
end
