source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gemspec

gem 'concurrent-ruby',         require: 'concurrent'

# TODO: move to gemspec when released
gem 'kit-app-container',       path: '../../libraries/kit-app-container'
gem 'kit-dummy-app-container', path: '../../libraries/kit-dummy-app-container'
gem 'kit-error',               path: '../../libraries/kit-error'
gem 'kit-organizer',           path: '../../libraries/kit-organizer'

# TODO: move this to `kit-dummy-app-container` gemspec when released
gem 'kit-router',              path: '../../libraries/kit-router'

group :development do
  gem 'kit-doc',               path: '../../libraries/kit-doc'
end

# TODO: clean this up
group :test, :development do
  gem 'activesupport'
  gem 'colorize'
  gem 'pry'
end
