source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gemspec

gem 'concurrent-ruby',         require: 'concurrent'

# TODO: move to gemspec when released
gem 'kit-app-container',       path: '../../libraries/kit-app-container'
gem 'kit-dummy_app_container', path: '../../libraries/kit-dummy_app_container'
gem 'kit-error',               path: '../../libraries/kit-error'
gem 'kit-log',                 path: '../../libraries/kit-log'
gem 'kit-organizer',           path: '../../libraries/kit-organizer'

# TODO: move this to `kit-dummy_app_container` gemspec when released
gem 'kit-router',              path: '../../libraries/kit-router'

# TODO: move this to `kit-router` gemspec when released
gem 'kit-engine',              path: '../../libraries/kit-engine'

group :development do
  gem 'kit-doc',               path: '../../libraries/kit-doc'

  gem 'awesome_print', github: 'rubykit/awesome_print', branch: 'feature/custom-nesting'
end

# TODO: clean this up
group :test, :development do
  gem 'activesupport'
  gem 'colorize'
  gem 'pry'
end
