source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Declare your gem's dependencies in kit-auth.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem 'dotenv-rails', require: 'dotenv/rails-now'

gem 'paranoia', require: 'paranoia'
gem 'doorkeeper', require: 'doorkeeper'

gem 'kit-domain', path: '../../libs/kit-domain' # DEV MODE
gem 'contracts', require: 'contracts' # DEV MODE

gem 'kit-organizer', path: '../../libs/kit-organizer' # DEV MODE
gem 'kit-pagination', path: '../../libs/kit-pagination' # DEV MODE
gem 'kit-router', path: '../../libs/kit-router' # DEV MODE
gem 'kit-error', path: '../../libs/kit-error' # DEV MODE
gem 'kit-active-admin', path: '../../libs/kit-active-admin', require: 'kit/active_admin' # DEV MODE

gem "slim-rails" # DEV MODE ? doesn't get loaded otherwise

gem "browser"  # DEV MODE ? doesn't get loaded otherwise

gem "jsonapi-rails" # DEV MODE ?

group :development do
  gem 'annotate', '~> 2.7', '>= 2.7.4'
end

group :development, :test do
  gem 'awesome_print'
  gem 'colorize'

  gem 'better_errors'

  gem 'pry'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'

  gem 'listen'
end

group :development, :test do
  gem 'kit-app-container', path: '../../libs/kit-app-container'

  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner'
end