# References:
# - https://github.com/codeclimate/test-reporter/blob/master/examples/multiple_suites.md#example-1

# CircleCI ---------------------------------------------------------------------

version: 2.1

# Docker -----------------------------------------------------------------------

# TODO: cleanup values that should live in Kit::Config

docker_ruby: &docker_ruby
  docker:
    - image: circleci/ruby:2.7.0
      environment:
        RAILS_ENV: 'test'
        RUBYOPT: '-W:no-deprecated'
        # Todo: kill this
        DATABASE_URL: 'postgres://root:password@127.0.0.1/kit_api_json_api_spec_TEST'
        PGHOST: localhost

    - image: circleci/postgres:12.2-ram
      environment:
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'password'
        POSTGRES_DB: 'kit_api_json_api_spec_TEST'

docker_ruby_no_db: &docker_ruby_no_db
  docker:
    - image: circleci/ruby:2.7.0


# Rspec ------------------------------------------------------------------------

commands:

  checkout-code:
    description: Checking out code
    steps:
      - checkout:
          path: ~/kit

  run-rspec:
    description: 'Run RSPEC'
    steps:
      - run:
          #command: |
          #  RAILS_ENV=circle bundle exec rspec
          command: |
            bundle exec rspec

  show-bundler-version:
    steps:
      - run:
          command: |
            bundle -v

  install-bundler:
    description: Install Gemfile.lock version of bundler
    steps:
      - run:
          command: |
            sudo gem install bundler:2.1.4

  install-gems:
    description: Install gems with Bundler.
    parameters:
      gems_path:
        type: string
        default: vendor/bundle
    steps:
      - run:
          command: |
            bundle check || bundle install --retry=3 --path=<< parameters.gems_path >>

  save-cache-gems:
    description: Save RubyGems to cache.
    parameters:
      key:
        description: The cache key to use. The key is immutable.
        type: string
    steps:
    - save_cache:
        key: << parameters.key >>-{{ checksum "Gemfile.lock"  }}
        paths:
        - vendor/bundle

  restore-cache-gems:
    description: Restore cached RubyGems.
    parameters:
      key:
        description: The cache key to use. The key is immutable.
        type: string
    steps:
    - restore_cache:
        keys:
        - << parameters.key >>-{{ checksum "Gemfile.lock"  }}


# kit-api-json-api -------------------------------------------------------------

  kit-api-json-api__save-cache-gems:
    steps:
      - save-cache-gems:
          key: kit-api-json-api|gems|{{ checksum "Gemfile.lock" }}

  kit-api-json-api__restore-cache-gems:
    steps:
      - restore-cache-gems:
          key: kit-api-json-api|gems|{{ checksum "Gemfile.lock" }}

  kit-api-json-api__prepare-database:
    description: 'Loading DBs schemas && running seed'
    steps:
      - run:
          command: |
            bundle exec rails db:schema:load:primary --trace
            bundle exec rails db:seed:fantasy_data

# kit-organizer ----------------------------------------------------------------

  kit-organizer__save-cache-gems:
    steps:
      - save-cache-gems:
          key: kit-organizer|gems|{{ checksum "Gemfile.lock" }}

  kit-organizer__restore-cache-gems:
    steps:
      - restore-cache-gems:
          key: kit-organizer|gems|{{ checksum "Gemfile.lock" }}

# kit-pagination ---------------------------------------------------------------

  kit-pagination__save-cache-gems:
    steps:
      - save-cache-gems:
          key: kit-pagination|gems|{{ checksum "Gemfile.lock" }}

  kit-pagination__restore-cache-gems:
    steps:
      - restore-cache-gems:
          key: kit-pagination|gems|{{ checksum "Gemfile.lock" }}


# Jobs -------------------------------------------------------------------------

jobs:

  code-climate-setup:
    <<: *docker_ruby_no_db
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p code_climate/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./code_climate/cc-test-reporter
            chmod +x ./code_climate/cc-test-reporter
      - persist_to_workspace:
          root: .
          paths:
            - code_climate/cc-test-reporter

  code-climate-upload-coverage:
    <<: *docker_ruby_no_db
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ~/workspace/code_climate/cc-test-reporter sum-coverage ~/workspace/code_climate/codeclimate.*.json -p 3 -o ~/workspace/code_climate/codeclimate.total.json
            ~/workspace/code_climate/cc-test-reporter upload-coverage -i ~/workspace/code_climate/codeclimate.total.json

  test-kit-api-json-api:
    working_directory: ~/kit/libraries/kit-api-json-api
    <<: *docker_ruby
    #executor: ruby/default
    steps:
      - checkout-code
      - attach_workspace:
          at: ~/workspace
      - install-bundler
      - show-bundler-version
      - kit-api-json-api__restore-cache-gems
      - install-gems
      - kit-api-json-api__save-cache-gems
      - kit-api-json-api__prepare-database
      - run-rspec
      - run:
          name: Copy coverage
          command: ~/workspace/code_climate/cc-test-reporter format-coverage -t simplecov -o ~/workspace/code_climate/codeclimate.kit-api-json-api.json coverage/.resultset.json
      - run:
          name: Update .resultset.json paths
          command: |
            sed -i 's|"name": "|"name": "kit-api-json-api/|g' ~/workspace/code_climate/codeclimate.kit-api-json-api.json
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - code_climate/codeclimate.kit-api-json-api.json
      - store_artifacts:
          path: ~/workspace/code_climate/codeclimate.kit-api-json-api.json
          destination: codeclimate.kit-api-json-api.json

  test-kit-organizer:
    working_directory: ~/kit/libraries/kit-organizer
    <<: *docker_ruby
    #executor: ruby/default
    steps:
      - checkout-code
      - attach_workspace:
          at: ~/workspace
      - install-bundler
      - show-bundler-version
      - kit-organizer__restore-cache-gems
      - install-gems
      - kit-organizer__save-cache-gems
      - run-rspec
      - run:
          name: Copy coverage
          command: ~/workspace/code_climate/cc-test-reporter format-coverage -t simplecov -o ~/workspace/code_climate/codeclimate.kit-organizer.json coverage/.resultset.json
      - run:
          name: Update .resultset.json paths
          command: |
            sed -i 's|"name": "|"name": "kit-organizer/|g' ~/workspace/code_climate/codeclimate.kit-organizer.json
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - code_climate/codeclimate.kit-organizer.json
      - store_artifacts:
          path: ~/workspace/code_climate/codeclimate.kit-organizer.json
          destination: codeclimate.kit-organizer.json

  test-kit-pagination:
    working_directory: ~/kit/libraries/kit-pagination
    <<: *docker_ruby_no_db
    #executor: ruby/default
    steps:
      - checkout-code
      - attach_workspace:
          at: ~/workspace
      - install-bundler
      - show-bundler-version
      - kit-pagination__restore-cache-gems
      - install-gems
      - kit-pagination__save-cache-gems
      - run-rspec
      - run:
          name: Copy coverage
          command: ~/workspace/code_climate/cc-test-reporter format-coverage -t simplecov -o ~/workspace/code_climate/codeclimate.kit-pagination.json coverage/.resultset.json
      - run:
          name: Update .resultset.json paths
          command: |
            sed -i 's|"name": "|"name": "kit-pagination/|g' ~/workspace/code_climate/codeclimate.kit-pagination.json
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - code_climate/codeclimate.kit-pagination.json
      - store_artifacts:
          path: ~/workspace/code_climate/codeclimate.kit-pagination.json
          destination: codeclimate.kit-pagination.json


# Workflows --------------------------------------------------------------------

workflows:

  test-all:
    jobs:
      - code-climate-setup
      - test-kit-api-json-api:
          requires:
            - code-climate-setup
      - test-kit-organizer:
          requires:
            - code-climate-setup
      - test-kit-pagination:
          requires:
            - code-climate-setup
      - code-climate-upload-coverage:
          requires:
            - test-kit-api-json-api
            - test-kit-organizer
            - test-kit-pagination
