version: 2.1

# Docker -----------------------------------------------------------------------

# TODO: cleanup values that should live in Kit::Config

docker_tests: &docker_tests
  docker:
    - image: circleci/ruby:2.7.0
      environment:
        RAILS_ENV: 'test'
        RUBYOPT: '-W:no-deprecated'
        # Todo: kill this
        DATABASE_URL: 'postgres://root:password@127.0.0.1/kit_api_json_api_spec_TEST'
        PGHOST: localhost

    - image: circleci/postgres:12.2-ram
      environment:
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'password'
        POSTGRES_DB: 'kit_api_json_api_spec_TEST'

# Rspec ------------------------------------------------------------------------

commands:

  checkout-code:
    description: Checking out code
    steps:
      - checkout:
          path: ~/kit

  run-rspec:
    description: 'Run RSPEC'
    steps:
      - run:
          #command: |
          #  RAILS_ENV=circle bundle exec rspec
          command: |
            bundle exec rspec

  show-bundler-version:
    steps:
      - run:
          command: |
            bundle -v

  install-bundler:
    description: Install Gemfile.lock version of bundler
    steps:
      - run:
          command: |
            sudo gem install bundler:2.1.3

  install-gems:
    description: Install gems with Bundler.
    parameters:
      gems_path:
        type: string
        default: vendor/bundle
    steps:
      - run:
          command: |
            bundle check || bundle install --retry=3 --path=<< parameters.gems_path >>

  save-cache-gems:
    description: Save RubyGems to cache.
    parameters:
      key:
        description: The cache key to use. The key is immutable.
        type: string
    steps:
    - save_cache:
        key: << parameters.key >>-{{ checksum "Gemfile.lock"  }}
        paths:
        - vendor/bundle

  restore-cache-gems:
    description: Restore cached RubyGems.
    parameters:
      key:
        description: The cache key to use. The key is immutable.
        type: string
    steps:
    - restore_cache:
        keys:
        - << parameters.key >>-{{ checksum "Gemfile.lock"  }}



# kit-api-json-api -------------------------------------------------------------

  kit-api-json-api__save-cache-gems:
    steps:
      - save-cache-gems:
          key: kit-api-json-api@gems-v1

  kit-api-json-api__restore-cache-gems:
    steps:
      - restore-cache-gems:
          key: kit-api-json-api@gems-v1

  kit-api-json-api__prepare-database:
    description: 'Loading DBs schemas && running seed'
    steps:
      - run:
          command: |
            bundle exec rails db:schema:load:primary --trace
            bundle exec rails db:seed:fantasy_data

# kit-organizer ----------------------------------------------------------------

  kit-organizer__save-cache-gems:
    steps:
      - save-cache-gems:
          key: kit-organizer@gems-v1

  kit-organizer__restore-cache-gems:
    steps:
      - restore-cache-gems:
          key: kit-organizer@gems-v1

# kit-pagination ---------------------------------------------------------------

  kit-pagination__save-cache-gems:
    steps:
      - save-cache-gems:
          key: kit-pagination@gems-v1

  kit-pagination__restore-cache-gems:
    steps:
      - restore-cache-gems:
          key: kit-pagination@gems-v1


# Jobs -------------------------------------------------------------------------

jobs:

  test-kit-api-json-api:
    working_directory: ~/kit/libraries/kit-api-json-api
    <<: *docker_tests
    #executor: ruby/default
    steps:
      - checkout-code
      - show-bundler-version
      - install-bundler
      - kit-api-json-api__restore-cache-gems
      - install-gems
      - kit-api-json-api__save-cache-gems
      - kit-api-json-api__prepare-database
      - run-rspec

  test-kit-organizer:
    working_directory: ~/kit/libraries/kit-organizer
    <<: *docker_tests
    #executor: ruby/default
    steps:
      - checkout-code
      - show-bundler-version
      - install-bundler
      - kit-organizer__restore-cache-gems
      - install-gems
      - kit-organizer__save-cache-gems
      - run-rspec

  test-kit-pagination:
    working_directory: ~/kit/libraries/kit-organizer
    <<: *docker_tests
    #executor: ruby/default
    steps:
      - checkout-code
      - show-bundler-version
      - install-bundler
      - kit-pagination__restore-cache-gems
      - install-gems
      - kit-pagination__save-cache-gems
      - run-rspec

workflows:

  test-all:
    jobs:
      - test-kit-api-json-api
      - test-kit-organizer
      - test-kit-pagination
