# References:
# - https://github.com/codeclimate/test-reporter/blob/master/examples/multiple_suites.md#example-1

# CircleCI ---------------------------------------------------------------------

version: 2.1

# Docker -----------------------------------------------------------------------

# TODO: cleanup values that should live in Kit::Config

docker_ruby: &docker_ruby
  docker:
    - image: circleci/ruby:3.0.0-node-browsers
      environment:
        RAILS_ENV: 'test'
        RUBYOPT: '-W:no-deprecated'
        # Todo: kill this
        DATABASE_URL: 'postgres://root:password@127.0.0.1/kit_api_json_api_spec_TEST'
        PGHOST: localhost

    - image: circleci/postgres:12.2-ram
      environment:
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'password'
        POSTGRES_DB: 'kit_api_json_api_spec_TEST'

docker_ruby_no_db: &docker_ruby_no_db
  docker:
    - image: circleci/ruby:3.0.0


# Rspec ------------------------------------------------------------------------

commands:

  checkout-code:
    description: Checking out code
    steps:
      - checkout:
          path: ~/kit

  # Gems related ---------------------------------------------------------------

  show-bundler-version:
    steps:
      - run:
          command: |
            bundle -v

  install-bundler:
    description: Install Gemfile.lock version of bundler
    steps:
      - run:
          command: |
            sudo gem install bundler:2.2.21

  install-gems:
    description: Install gems with Bundler.
    parameters:
      gems_path:
        type: string
        default: vendor/bundle
    steps:
      - run:
          command: |
            bundle check || bundle install --retry=3 --path=<< parameters.gems_path >>

  save-cache-gems:
    description: Save RubyGems to cache.
    parameters:
      project:
        description: Target library / domain.
        type: string
    steps:
    - save_cache:
        key: << parameters.project >>|gems|{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

  restore-cache-gems:
    description: Restore cached RubyGems.
    parameters:
      project:
        description: Target library / domain.
        type: string
    steps:
    - restore_cache:
        keys:
        - << parameters.project >>|gems|{{ checksum "Gemfile.lock" }}

  # Rspec ----------------------------------------------------------------------

  run-rspec:
    description: 'Run RSPEC'
    steps:
      - run:
          #command: |
          #  RAILS_ENV=circle bundle exec rspec
          command: |
            SIMPLECOV=true bundle exec rspec

  # Rspec ----------------------------------------------------------------------

  save-simple-cov-coverage:
    description: 'Transform SimpleCov code coverage & save it to workspace'
    parameters:
      project:
        description: Target library / domain.
        type: string
    steps:
      - run:
          name: Format coverage for CodeClimate
          command: ~/workspace/code_climate/cc-test-reporter format-coverage -t simplecov -o ~/workspace/code_climate/codeclimate.<< parameters.project >>.json coverage/.resultset.json
      - run:
          name: Update .resultset.json paths to avoid collisions
          command: |
            sed -i 's|"name": "|"name": "<< parameters.project >>/|g' ~/workspace/code_climate/codeclimate.<< parameters.project >>.json
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - code_climate/codeclimate.<< parameters.project >>.json
      #- store_artifacts:
      #    path: ~/workspace/code_climate/codeclimate.<< parameters.project >>.json
      #    destination: codeclimate.<< parameters.project >>.json

  # kit-auth -------------------------------------------------------------------

  kit-auth__prepare-database:
    description: 'Loading DBs schemas && running seed'
    steps:
      - run:
          command: |
            bundle exec rails db:schema:load:primary_ops --trace
            bundle exec rails db:seed:applications

  # kit-api --------------------------------------------------------------------

  kit-api__prepare-database:
    description: 'Loading DBs schemas && running seed'
    steps:
      - run:
          command: |
            bundle exec rails db:schema:load:primary --trace
            bundle exec rails db:seed:fantasy_data


# Jobs -------------------------------------------------------------------------

jobs:

  code-climate-setup:
    <<: *docker_ruby_no_db
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p code_climate/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./code_climate/cc-test-reporter
            chmod +x ./code_climate/cc-test-reporter
      - persist_to_workspace:
          root: .
          paths:
            - code_climate/cc-test-reporter

  code-climate-upload-coverage:
    <<: *docker_ruby_no_db
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ~/workspace/code_climate/cc-test-reporter sum-coverage ~/workspace/code_climate/codeclimate.*.json -p 5 -o ~/workspace/code_climate/codeclimate.total.json
            ~/workspace/code_climate/cc-test-reporter upload-coverage -i ~/workspace/code_climate/codeclimate.total.json

  test-kit-auth:
    working_directory: ~/kit/domains/kit-auth
    <<: *docker_ruby
    #executor: ruby/default
    steps:
      - checkout-code
      - attach_workspace:
          at: ~/workspace
      - install-bundler
      - show-bundler-version
      - restore-cache-gems:
          project: kit-auth
      - install-gems
      - save-cache-gems:
          project: kit-auth
      - kit-auth__prepare-database
      - run-rspec
      - save-simple-cov-coverage:
          project: kit-auth

  test-kit-api:
    working_directory: ~/kit/libraries/kit-api
    <<: *docker_ruby
    #executor: ruby/default
    steps:
      - checkout-code
      - attach_workspace:
          at: ~/workspace
      - install-bundler
      - show-bundler-version
      - restore-cache-gems:
          project: kit-api
      - install-gems
      - save-cache-gems:
          project: kit-api
      - kit-api__prepare-database
      - run-rspec
      - save-simple-cov-coverage:
          project: kit-api

  test-kit-contract:
    working_directory: ~/kit/libraries/kit-contract
    <<: *docker_ruby
    #executor: ruby/default
    steps:
      - checkout-code
      - attach_workspace:
          at: ~/workspace
      - install-bundler
      - show-bundler-version
      - restore-cache-gems:
          project: kit-contract
      - install-gems
      - save-cache-gems:
          project: kit-contract
      - run-rspec
      - save-simple-cov-coverage:
          project: kit-contract

  test-kit-organizer:
    working_directory: ~/kit/libraries/kit-organizer
    <<: *docker_ruby
    #executor: ruby/default
    steps:
      - checkout-code
      - attach_workspace:
          at: ~/workspace
      - install-bundler
      - show-bundler-version
      - restore-cache-gems:
          project: kit-organizer
      - install-gems
      - save-cache-gems:
          project: kit-organizer
      - run-rspec
      - save-simple-cov-coverage:
          project: kit-organizer

  test-kit-pagination:
    working_directory: ~/kit/libraries/kit-pagination
    <<: *docker_ruby_no_db
    #executor: ruby/default
    steps:
      - checkout-code
      - attach_workspace:
          at: ~/workspace
      - install-bundler
      - show-bundler-version
      - restore-cache-gems:
          project: kit-pagination
      - install-gems
      - save-cache-gems:
          project: kit-pagination
      - run-rspec
      - save-simple-cov-coverage:
          project: kit-pagination


# Workflows --------------------------------------------------------------------

workflows:

  test-all:
    jobs:
      - code-climate-setup
      - test-kit-auth:
          requires:
            - code-climate-setup
      - test-kit-api:
          requires:
            - code-climate-setup
      - test-kit-contract:
          requires:
            - code-climate-setup
      - test-kit-organizer:
          requires:
            - code-climate-setup
      - test-kit-pagination:
          requires:
            - code-climate-setup
      - code-climate-upload-coverage:
          requires:
            - test-kit-auth
            - test-kit-api
            - test-kit-contract
            - test-kit-organizer
            - test-kit-pagination
