source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Declare your gem's dependencies in kit-dummy-app-container.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

gem 'rails'
gem 'kit-organizer',     path: '../../libs/kit-organizer'
gem 'kit-app-container', path: '../../libs/kit-app-container'

group :development do
  gem 'annotate', '~> 2.7', '>= 2.7.4'
end

group :development, :test do
  gem 'awesome_print'
  gem 'colorize'

  gem 'better_errors'

  gem 'pry'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'

  gem 'listen'
end

group :development, :test do
  #gem 'kit-app-container', path: '../../libs/kit-app-container'

  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner'
end