source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gemspec

gem 'dotenv-rails', require: 'dotenv/rails-now'

gem 'paranoia', require: 'paranoia'

gem 'kit-active-admin', path: '../../libraries/kit-active-admin', require: 'kit/active_admin' # DEV MODE
gem 'kit-contract',     path: '../../libraries/kit-contract' # DEV MODE
gem 'kit-domain',       path: '../../libraries/kit-domain' # DEV MODE
gem 'kit-organizer',    path: '../../libraries/kit-organizer' # DEV MODE

gem 'slim-rails' # DEV MODE ? doesn't get loaded otherwise

group :development do
  gem 'annotate', '~> 2.7', '>= 2.7.4'
end

group :development, :test do
  gem 'awesome_print'
  gem 'colorize'

  gem 'better_errors'

  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
end

group :development, :test do
  gem 'kit-app-container', path: '../../libraries/kit-app-container'

  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner'
end
