source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gemspec

gem 'kit-contract',   path: '../../libraries/kit-contract' # GEMSPEC
gem 'kit-error',      path: '../../libraries/kit-error' # GEMSPEC
gem 'kit-log',        path: '../../libraries/kit-log' # GEMSPEC
gem 'kit-organizer',  path: '../../libraries/kit-organizer' # GEMSPEC
gem 'kit-pagination', path: '../../libraries/kit-pagination' # GEMSPEC

group :test, :development do
  gem 'puma'

  gem 'listen'

  gem 'json_schemer'

  gem 'pry'
  gem 'pry-stack_explorer'

  gem 'pg'

  gem 'kit-dotenv',              path: '../../libraries/kit-dotenv'
  gem 'kit-dotenv-rails',        path: '../../libraries/kit-dotenv', require: 'kit/dotenv/rails-now'

  gem 'kit-app-container',       path: '../../libraries/kit-app-container' # DEV MODE
  gem 'kit-domain',              path: '../../libraries/kit-domain' # DEV MODE
  gem 'kit-dummy-app-container', path: '../../libraries/kit-dummy-app-container' # DEV MODE
  gem 'kit-engine',              path: '../../libraries/kit-engine' # DEV MODE
  gem 'kit-router',              path: '../../libraries/kit-router' # DEV MODE

  gem 'kit-rspec-formatter',     path: '../../libraries/kit-rspec-formatter' # DEV MODE

  gem 'seedbank'
end

group :development do
  gem 'kit-doc',                 path: '../../libraries/kit-doc'
end

group :development, :test do
  # Profiling
  gem 'derailed_benchmarks'
  gem 'flamegraph'
  gem 'memory_profiler'
  gem 'rack-mini-profiler', require: false
  gem 'ruby-prof'
  gem 'stackprof'

  # Seeding
  gem 'factory_bot_rails', '~> 6.1'

  # Logging
  #gem 'awesome_print', path: '../../../awesome_print'
  gem 'awesome_print', github: 'rubykit/awesome_print', branch: 'feature/custom-nesting'
end

group :test do
  gem 'faker'

  gem 'database_cleaner'

  gem 'rspec-rails'

  gem 'test-prof'
end
