begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'bundler/gem_tasks'

require_relative 'config/kit_runtime_config'
require 'kit/dummy-app-container/rails_application'

Rails.application.load_tasks

import 'tasks/documentation.rake'

require 'seedbank'
Seedbank.seeds_root = File.expand_path('./spec/dummy/db/seeds', __dir__)
Seedbank.load_tasks if defined?(Seedbank)

begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)
rescue LoadError # rubocop:disable Lint/SuppressedException
end
