source 'https://rubygems.org'

gemspec

gem 'kit-active-admin', path: '../../libraries/kit-active-admin'
gem 'kit-contract',     path: '../../libraries/kit-contract'
gem 'kit-organizer',    path: '../../libraries/kit-organizer'
