config_default: &config_default
  adapter:  <%= ENV['DATABASE_ADAPTER'] || 'postgresql' %>
  encoding: utf8
  pool:     <%= (ENV['DATABASE_POOL'] || ENV['MAX_THREADS'] || 5) %>

# Readonly mode | expected privileges: [CONNECT, SELECT]
config_default_readonly: &config_default_readonly
  <<:  *config_default
  url: <%= ENV['DATABASE_URL_READONLY'] %>

# Write mode | expected privileges: readonly_mode + [INSERT, UPDATE, DELETE]
config_default_write: &config_default_write
  <<:  *config_default
  url: <%= ENV['DATABASE_URL_WRITE'] %>

# Operation mode | expected privileges: write_mode + [CREATE, REFERENCES, TRIGGER, TRUNCATE, USAGE]
config_default_ops: &config_default_ops
  <<:  *config_default
  url: <%= ENV['DATABASE_URL_OPS'] %>

# ------------------------------------------------------------------------------

databases_config: &databases_config
  primary:
    adapter: nulldb
  primary_readonly:
    <<: *config_default_readonly
  primary_write:
    <<: *config_default_write
  primary_ops:
    <<: *config_default_ops

# ------------------------------------------------------------------------------
# All ENVs behave the same way

production:
  <<: *databases_config

development:
  <<: *databases_config

test:
  <<: *databases_config
