source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Declare your gem's dependencies in kit_json_api.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem 'rails'

gem 'kit-organizer',           path: '../../libs/kit-organizer' # GEMSPEC

gem 'sassc'

group :test, :development do
  gem 'pry'

  gem 'kit-dotenv-rails',        path: '../../libs/kit-dotenv', require: "kit/dotenv/rails-now"

  gem 'kit-app-container',       path: '../../libs/kit-app-container' # DEV MODE
  gem 'kit-dummy-app-container', path: '../../libs/kit-dummy-app-container' # DEV MODE
  gem 'kit-engine',              path: '../../libs/kit-engine' # DEV MODE
  gem 'kit-domain',              path: '../../libs/kit-domain' # DEV MODE
  gem 'kit-router',              path: '../../libs/kit-router' # DEV MODE

  gem 'seedbank'
end

group :development do
  gem 'yard-kit',                path: '../../libs/yard-kit'
  gem 'rubocop', '~> 0.81.0'
end
