begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'bundler/gem_tasks'

require_relative 'config/kit_runtime_config'
require 'kit/dummy-app-container/rails_application'

Rails.application.load_tasks

begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  #task :default => :spec
rescue LoadError
  # no rspec available
end