source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gemspec

gem 'kit-dotenv',              path: '../../libraries/kit-dotenv'
gem 'kit-dotenv-rails',        path: '../../libraries/kit-dotenv', require: 'kit/dotenv/rails-now'

gem 'jsonapi-rails' # DEV MODE ?

# TODO: kill this, only needed because AA is not yet compatible with Rails 6.1
gem 'inherited_resources', github: 'activeadmin/inherited_resources'
# TODO: kill this, only needed because AA is not yet compatible with Rails 6.1
gem 'activeadmin',         github: 'activeadmin/activeadmin', ref: 'f7b24c8e7816cd3e655e64cfa2c44d8b0a8b696f'

gem 'kit-active-admin', path: '../../libraries/kit-active-admin', require: 'kit/active_admin' # DEV MODE
gem 'kit-contract',     path: '../../libraries/kit-contract' # DEV MODE
gem 'kit-doc',          path: '../../libraries/kit-doc' # DEV MODE
gem 'kit-domain',       path: '../../libraries/kit-domain' # DEV MODE
gem 'kit-engine',       path: '../../libraries/kit-engine' # DEV MODE
gem 'kit-error',        path: '../../libraries/kit-error' # DEV MODE
gem 'kit-log',          path: '../../libraries/kit-log' # DEV MODE
gem 'kit-organizer',    path: '../../libraries/kit-organizer' # DEV MODE
gem 'kit-pagination',   path: '../../libraries/kit-pagination' # DEV MODE
gem 'kit-router',       path: '../../libraries/kit-router' # DEV MODE

gem 'browser'  # DEV MODE ? doesn't get loaded otherwise
gem 'doorkeeper', require: 'doorkeeper'
gem 'paranoia',   require: 'paranoia', github: 'walski/paranoia', branch: 'rails-6-1'
gem 'sidekiq'  # DEV MODE ? doesn't get loaded otherwise
gem 'slim-rails' # DEV MODE ? doesn't get loaded otherwise

group :development do
  gem 'annotate', '~> 2.7', '>= 2.7.4'
end

group :development, :test do
  gem 'awesome_print'
  gem 'colorize'

  gem 'better_errors'

  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'

  gem 'listen'

  gem 'capybara'
  gem 'webdrivers', '~> 4.0', require: false
end

group :development, :test do
  gem 'kit-app-container',       path: '../../libraries/kit-app-container' # DEV MODE
  gem 'kit-dummy-app-container', path: '../../libraries/kit-dummy-app-container' # DEV MODE
  gem 'kit-rspec-formatter',     path: '../../libraries/kit-rspec-formatter' # DEV MODE

  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner'
end
