source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gemspec

gem 'kit-dotenv',          path: '../../libraries/kit-dotenv'
gem 'kit-dotenv-rails',    path: '../../libraries/kit-dotenv', require: 'kit/dotenv/rails-now'

gem 'kit-active-admin',    path: '../../libraries/kit-active-admin', require: 'kit/active_admin' # DEV MODE
gem 'kit-contract',        path: '../../libraries/kit-contract' # DEV MODE
gem 'kit-doc',             path: '../../libraries/kit-doc' # DEV MODE
gem 'kit-domain',          path: '../../libraries/kit-domain' # DEV MODE
gem 'kit-engine',          path: '../../libraries/kit-engine' # DEV MODE
gem 'kit-error',           path: '../../libraries/kit-error' # DEV MODE
gem 'kit-log',             path: '../../libraries/kit-log' # DEV MODE
gem 'kit-organizer',       path: '../../libraries/kit-organizer' # DEV MODE
gem 'kit-pagination',      path: '../../libraries/kit-pagination' # DEV MODE
gem 'kit-router',          path: '../../libraries/kit-router' # DEV MODE
gem 'kit-support',         path: '../../libraries/kit-support' # DEV MODE
gem 'kit-view_components', path: '../../libraries/kit-view_components' # DEV MODE

gem 'kit_theme_bootstrap', git: 'https://github.com/rubykit/kit_theme_bootstrap', branch: 'main'

gem 'browser'  # DEV MODE ? doesn't get loaded otherwise
gem 'doorkeeper', require: 'doorkeeper'
gem 'paranoia',   require: 'paranoia'
gem 'sidekiq'  # DEV MODE ? doesn't get loaded otherwise
gem 'slim-rails' # DEV MODE ? doesn't get loaded otherwise

# TMP: because of the require
gem 'view_component', require: 'view_component/engine'

gem 'bootstrap-email', '>= 1.0.0.alpha'
gem 'kit_liquid_rails'
#gem 'letter_opener', git: 'https://github.com/Kulgar/letter_opener.git', group: :development
gem 'letter_opener', group: :development
gem 'liquid', '~> 5.0', '>= 5.0.1'

gem 'i18n-interpolate_nested'

group :development do
  gem 'annotate', '~> 2.7', '>= 2.7.4'
end

group :development, :test do
  gem 'puma'

  gem 'awesome_print', github: 'rubykit/awesome_print', branch: 'feature/custom-nesting'
  gem 'colorize'

  gem 'better_errors'

  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'

  gem 'listen'

  gem 'capybara'
  gem 'webdrivers', '~> 4.0', require: false
end

group :development, :test do
  gem 'kit-app-container',       path: '../../libraries/kit-app-container' # DEV MODE
  gem 'kit-dummy_app_container', path: '../../libraries/kit-dummy_app_container' # DEV MODE
  gem 'kit-rspec_formatter',     path: '../../libraries/kit-rspec_formatter' # DEV MODE

  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner'
end
