begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'bundler/gem_tasks'

require_relative 'config/kit_runtime_config'
require 'kit/dummy_app_container/rails_application'

APP_RAKEFILE = File.expand_path('spec/dummy/Rakefile', __dir__)
load 'rails/tasks/engine.rake'

if !defined?(RAKEFILE_LOADED_RAILS_TASKS) || !RAKEFILE_LOADED_RAILS_TASKS
  # NOTE: Some tasks cause both the Gem Rakefile && dummy app one to be loaded.
  Rails.application.load_tasks
  RAKEFILE_LOADED_RAILS_TASKS = true
end

import 'tasks/documentation.rake'
import 'tasks/router.rake'

require 'seedbank'
Seedbank.seeds_root = File.expand_path('db/seeds', __dir__)
Seedbank.load_tasks if defined?(Seedbank)
