begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'bundler/gem_tasks'

require_relative 'config/kit_runtime_config'
require 'kit/dummy_app_container/rails_application'

ENGINE_ROOT = __dir__
Rails.application.load_tasks

import 'tasks/documentation.rake'
import 'tasks/router.rake'

require 'seedbank'
Seedbank.seeds_root = File.expand_path('db/seeds', __dir__)
Seedbank.load_tasks if defined?(Seedbank)
