source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

# Declare your gem's dependencies in kit_api_json_api.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem 'kit-contract',   path: '../../libraries/kit-contract' # GEMSPEC
gem 'kit-error',      path: '../../libraries/kit-error' # GEMSPEC
gem 'kit-organizer',  path: '../../libraries/kit-organizer' # GEMSPEC
gem 'kit-pagination', path: '../../libraries/kit-pagination' # GEMSPEC

group :test, :development do
  gem 'pry'
  gem 'pry-stack_explorer'

  gem 'pg'

  gem 'kit-dotenv',        path: '../../libraries/kit-dotenv'
  gem 'kit-dotenv-rails',  path: '../../libraries/kit-dotenv', require: 'kit/dotenv/rails-now'

  gem 'kit-app-container',       path: '../../libraries/kit-app-container' # DEV MODE
  gem 'kit-domain',              path: '../../libraries/kit-domain' # DEV MODE
  gem 'kit-dummy-app-container', path: '../../libraries/kit-dummy-app-container' # DEV MODE
  gem 'kit-engine',              path: '../../libraries/kit-engine' # DEV MODE
  gem 'kit-router',              path: '../../libraries/kit-router' # DEV MODE

  gem 'seedbank'
end

group :development do
  gem 'kit-doc-yard',            path: '../../libraries/kit-doc-yard'
end

group :test do
  gem 'ruby-prof'
  gem 'stackprof'
  gem 'test-prof'
end
