source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Declare your gem's dependencies in kit-auth.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem 'dotenv-rails', require: 'dotenv/rails-now'

gem 'paranoia', require: 'paranoia'
gem 'doorkeeper', require: 'doorkeeper'

gem 'kit-engine', path: '../kit-engine' # DEV MODE
gem 'contracts', require: 'contracts' # DEV MODE

gem 'interactor', path: '../../gems/interactor' # DEV MODE
gem 'activeadmin_tables', path: '../../gems/activeadmin_tables' # DEV MODE

gem "slim-rails" # DEV MODE ? doesn't get loaded otherwise
gem "simple_form" # DEV MODE ? doesn't get loaded otherwise


group :development do
  gem 'annotate', '~> 2.7', '>= 2.7.4'
end

group :development, :test do
  gem 'awesome_print'
  gem 'colorize'

  gem 'better_errors'

  gem 'pry'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'
end

group :development, :test do
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner'
end