source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.2'

gem 'rails', '~> 6.0.0.rc2'
gem 'puma'

gem 'kit-app-container', path: '../../kit/libs/kit-app-container' # DEV MODE

gem 'kit-auth',          path: '../../kit/domains/kit-auth' # DEV MODE
gem 'kit-geolocation',   path: '../../kit/domains/kit-geolocation' # DEV MODE
gem 'kit-payment',       path: '../../kit/domains/kit-payment' # DEV MODE

group :development do
  gem 'listen'

  gem 'better_errors'

  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'

  gem 'awesome_print'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  #gem 'capybara', '>= 2.15'
  #gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  #gem 'chromedriver-helper'

  gem 'rspec-rails'
  gem 'factory_bot_rails', require: false
  gem 'database_cleaner'
  gem 'faker'
  gem 'fuubar'
  gem 'vcr', '~> 4.0'
  gem 'webmock', '~> 2.1'
  gem 'timecop'
end
