source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.2'

gem 'rails', '~> 5.2.3'
gem 'puma', '~> 3.11'

# Reduces boot times through caching; required in config/boot.rb
#gem 'bootsnap', '>= 1.1.0', require: false

gem 'kit-auth', path: '../../kit/kit-auth' # DEV MODE
gem 'doorkeeper', require: 'doorkeeper' # DEV MODE

gem 'interactor', path: '../../gems/interactor' # DEV MODE
gem 'activeadmin_tables', path: '../../gems/activeadmin_tables' # DEV MODE

group :development do
  gem 'listen'

  gem 'better_errors'

  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'

  gem 'awesome_print'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  #gem 'capybara', '>= 2.15'
  #gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  #gem 'chromedriver-helper'

  gem 'rspec-rails'
  gem 'factory_bot_rails', require: false
  gem 'database_cleaner'
  gem 'faker'
  gem 'fuubar'
  gem 'vcr', '~> 4.0'
  gem 'webmock', '~> 2.1'
  gem 'timecop'
end
