inherit_from: ../../.rubocop_shared.yml

# Note: needed because somehow running rubocop in the top level dir VS projects subdirectories has slightly different behaviours.
Lint/RedundantCopDisableDirective:
  Enabled: false
