source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gemspec

gem 'kit-app_container',       path: '../../libraries/kit-app_container' # DEV MODE
gem 'kit-contract',            path: '../../libraries/kit-contract'
gem 'kit-dummy_app_container', path: '../../libraries/kit-dummy_app_container' # DEV MODE
gem 'kit-engine',              path: '../../libraries/kit-engine' # DEV MODE
gem 'kit-log',                 path: '../../libraries/kit-log' # DEV MODE
gem 'kit-organizer',           path: '../../libraries/kit-organizer' # DEV MODE
gem 'kit-support',             path: '../../libraries/kit-support' # DEV MODE

group :development do
  gem 'kit-doc',               path: '../../libraries/kit-doc'
  gem 'pry'
end
