source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gemspec

gem 'kit-app-container',       path: '../../libraries/kit-app-container' # DEV MODE
gem 'kit-contract',            path: '../../libraries/kit-contract'
gem 'kit-dummy-app-container', path: '../../libraries/kit-dummy-app-container' # DEV MODE
gem 'kit-engine',              path: '../../libraries/kit-engine' # DEV MODE
gem 'kit-organizer',           path: '../../libraries/kit-organizer' # DEV MODE

group :development do
  gem 'kit-doc',               path: '../../libraries/kit-doc'
  gem 'pry'
end
