source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

gemspec

gem 'kit-support', path: '../../libraries/kit-support'

group :development do
  gem 'pry'
end
