begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'bundler/gem_tasks'

import 'tasks/documentation.rake'
import 'specs/dummy/tasks/documentation.rake'
